---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull
  namespace: v1check-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBlxIRaCqIOTboQWxtOThp9x+dOQ+0EJqWIU4fawKDjcyPfr1QfB45YIDGHS99eT87JowYL1rNWzFFIWAMLB4DdPpPTOAz8oIC/HjdD9IvgPgI9TRJ+6mITnetTG1VxB1x6uJC5F8TtPIe0WkfGFqpoMFixS9i6pkGMIycYsZI12wHDn5feRSmfL+0QHL234Whu4RyqRFKCxAjpddc7RJyJldcoD3rXkM55JGRj9J8liu6OJK3cxTJ2hxKyRy0lAtqZxKfn6m08nTajvT+Ge5RtbJdNzhsjfWoVKqN/W6AvgQ8tTJ8rJdpv2OK483HDRSNWMDnfkv3sMyLIntoMEvA/9otZYS43CECjTfwO9t6TOX2QACV21JUKHPDomqq2Cog49a37/8WBtm4IFz2j7yxDChunHH5H5xlkxTZknhshDy2mDD6b3ZbfJ6Mcx0Oc+QJoOIUlq3e8y9urWPS5J8liBAxfVauZVpEz3KDolrOE1Tu1NYdSYKO/rQuAwmVxvtqxCG//qOMJ5oPrFYPJw2b6R3AI7IcXD8sBO8+xWytrnjm1shFHQ14qGyhWBCRRBbnI5fIZ4cmazGdTgty7W8Nk6fqnHI9s5zoWQM/K50wdMUCnizSRdOjHgcRgPbsg0hDBPztKu7oiK5bHSwQaDQnO4MtTcx0YnQfXqQCZoa/t+A7WlCXXuxPB4FFm16nMYV0SLiGRj4m9YySAi9FWHa6GhqFR/xGoBIRywW0tjQJSy/K3npWIFfR6JK3iiOdieWHGvOGyDpE/0BLrX3XPmETQiXpGYmHnYFW0B3KE7UWoDNnoDk/fPfk6JnWHhbrEUhxEe9400eMSCuehMkWEheEKpbvHw9Idb3DvF9cEzuQ2aXUPKzbptTB9m+V+uaUVOd4dHnletI0Q344C4X3L+v2GrbNu99In+wkd8f4eWNDGQ/yLaDdridsCoa+JfJO8oqfbW81iDkiiT0ivojOnILKLNuKHmmZ/
  template:
    metadata:
      name: harbor-pull
      namespace: v1check-dev
    type: kubernetes.io/dockerconfigjson
